name: Rust Beta

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust Beta Toolchain
      run: rustup toolchain install beta
    - name: Beta Rust Build
      run: cargo +beta test
    - name: Run beta application
      run: cargo +beta run
