name: Rust Nightly

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust Nightly Toolchain
      run: rustup toolchain install nightly
    - name: Nightly Rust Build
      run: cargo +nightly test
    - name: Run nightly application
      run: cargo +nightly run
